version: '3.9'
services:
  redis:
    container_name: redis
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
    env_file:
      - config.yaml
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: search_engine
    ports:
      - '5431:5432'
