basePath: /
definitions:
  models.ApiError:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  models.Document:
    properties:
      country:
        description: URL of article
        type: string
      lat:
        description: Latitude of city
        type: string
      lng:
        description: Longitude of city
        type: string
      name:
        description: Title of article
        type: string
    type: object
  swagger.SwaggerResponse:
    properties:
      country:
        description: Author of article
        example: Austria
        type: string
      location:
        description: Topics of article
        example: 48.20849,16.37208
        type: string
      name:
        description: URL of doc
        example: Wien
        type: string
    type: object
  swagger.SwaggerSearchResponse:
    properties:
      response:
        items:
          $ref: '#/definitions/swagger.SwaggerResponse'
        type: array
      suggestion:
        items:
          $ref: '#/definitions/swagger.SwaggerSuggestion'
        type: array
      total:
        example: 1
        type: integer
    type: object
  swagger.SwaggerSuggestion:
    properties:
      incr:
        example: false
        type: boolean
      payload:
        example: Pair
        type: string
      score:
        example: 70.7
        type: number
      term:
        example: Pair
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: This is a search engine built with Redisearch
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Redisearch Search Engine
  version: "1.0"
paths:
  /api/document:
    post:
      parameters:
      - description: The body to create a Redis document for an article
        in: body
        name: Body
        required: true
        schema:
          items:
            $ref: '#/definitions/models.Document'
          type: array
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.Document'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ApiError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Post documents to Redisearch
      tags:
      - Document
  /api/document/delete/{documentName}:
    delete:
      operationId: documentName
      parameters:
      - description: search term
        in: path
        name: documentName
        required: true
        type: string
      responses:
        "200":
          description: Ok
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Delete documents from Redisearch
      tags:
      - Document
  /api/index/create:
    post:
      responses:
        "200":
          description: Ok
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Create Redis index for BestPracticer guides
      tags:
      - Index
  /api/index/delete:
    delete:
      responses:
        "200":
          description: Ok
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Delete all documents from Redisearch
      tags:
      - Index
  /api/search/{term}:
    get:
      operationId: article search
      parameters:
      - description: Search by keyword
        in: path
        name: term
        required: true
        type: string
      - description: Sort by field
        in: query
        name: sort
        type: string
      - description: Ascending?
        in: query
        name: ascending
        type: boolean
      - description: Limit number of results
        in: query
        name: limit
        type: integer
      - description: Is it a geo query
        in: query
        name: geo
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/swagger.SwaggerSearchResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Search Redisearch documents
      tags:
      - Search
  /api/search/geo:
    get:
      operationId: country geo search
      parameters:
      - description: Longitude
        in: query
        name: longitude
        required: true
        type: string
      - description: Latitude
        in: query
        name: latitude
        required: true
        type: string
      - description: Radius
        in: query
        name: radius
        required: true
        type: string
      - description: Limit number of results
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/swagger.SwaggerSearchResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Search Redisearch documents
      tags:
      - Search
schemes:
- http
- https
swagger: "2.0"
